### ISSUE TITLE
run code pre_process_UNSC.py and predict_UNSC.py

### ISSUE THREAD

**Issue by qzqzzw** [atreyasha/sentiment-argument-mining#12]
![issue1](https://user-images.githubusercontent.com/57550503/102445755-37635d00-4067-11eb-9f16-f5de0c554693.png)
Hello professor, I am a Chinese student. I encountered this problem when running your code, I hope you can answer it

**Comment by atreyasha** [comment]
HI @qzqzzw,

1. Regarding `pre_process_UNSC.py`, I am not able to reproduce this error when I run it locally. In your case, it appears the file `docs.RData` is found but cannot be read. Could you try deleting `docs.RData` and `docs_meta.RData` and then download them again using the `init.sh` script? If this does not work, could you also check the read permissions of the respective `*.RData` files?

2. Regarding prediction, try executing the following command:

```python
python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5
```

PS: For the prediction command, you need to have downloaded the model using `git lfs`. If the model `./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5` is not present, try installing `git-lfs` and then run `git lfs pull` in this repository to download the model.

Hope these help. Let me know if there are still errors and we can work on fixing them.

**Comment by qzqzzw** [comment]
@atreyasha Hello professor, I executed the following command:
`python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5`
But this problem occurred：
![1](https://user-images.githubusercontent.com/57550503/102703475-366e3d80-42aa-11eb-9241-0b8973ae4a84.png)
Is this missing the logging package?I installed this package in my virtual environment, but the above error is still reported
![2](https://user-images.githubusercontent.com/57550503/102703494-77665200-42aa-11eb-9405-170e98198642.png)

**Comment by atreyasha** [comment]
Hi @qzqzzw. I can confirm this as a bug, no need to install anything extra in the virtual environment.

I will fix it tomorrow and will let you know.

**Comment by qzqzzw** [comment]
Professor atreyasha, thank you very much。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Atreya Shankar"<notifications@github.com&gt;; 
发送时间: 2020年12月20日(星期天) 上午10:27
收件人: "atreyasha/sentiment-argument-mining"<sentiment-argument-mining@noreply.github.com&gt;; 
抄送: "＊Away＊"<331337507@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [atreyasha/sentiment-argument-mining] run code pre_process_UNSC.py and predict_UNSC.py (#12)





 
Hi @qzqzzw. I can confirm this is a bug, no need to install anything extra in the virtual environment.
 
I will fix it tomorrow and will let you know.

**Comment by atreyasha** [comment]
Hi @qzqzzw,

This error arose because of cross-module imports which don't allow `logger` from one module being used in another.

With https://github.com/atreyasha/sentiment-argument-mining/commit/64a99762202942f1dc249c33255159c7d9d26a15, I removed this capability so now this error should not occur. Instead, an error will be thrown saying that the user did not preprocess the relevant data beforehadn.

Now if you want to run the prediction workflow, you would need to execute the following in this order:

1. `python3 pre_process_USElectionDebates.py`
2. `python3 pre_process_UNSC.py`
3. `python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5`

**Comment by qzqzzw** [comment]
@atreyasha Hello professor, I run `python3 pre_process_USElectionDebates.py`
An error occurred：
![1](https://user-images.githubusercontent.com/57550503/102841283-9ba76780-443f-11eb-9bea-e6345a8a423d.png)
module 'bert' has no attributue 'fetch_google_albert_models'.
how to solve this problem？

**Comment by atreyasha** [comment]
Hi @qzqzzw,

Sorry about that, I thought I had fixed this bug some time back. This bug arises because of a wrongly installed `bert` pypi package which should not have been a dependency in the first place.

https://github.com/atreyasha/sentiment-argument-mining/commit/541b0352f08c896589061ffc4b0fcde9e10ec8c4 should fix this. I would suggest deleting and re-installing your virtual environment with the new `requirements.txt` file to get rid of any legacy code.

**Comment by atreyasha** [comment]
Found another bug with the python dependencies, the latest commit https://github.com/atreyasha/sentiment-argument-mining/commit/8a736ccbb9eadb4fd3bd519420e6434d702e4757 should fix this.

**Comment by qzqzzw** [comment]
@atreyasha Hello professor, I pulled the code again and re-installed  virtual environment with the new requirements.txt file,An error occurred：module 'bert' has no attributue 'fetch_google_albert_models'.
I modified requirements.txt and change tensorflow-gpu to tensorflow.
![1](https://user-images.githubusercontent.com/57550503/102865565-ebeaed80-4470-11eb-9d2c-fd4f29fc626f.png)
![2](https://user-images.githubusercontent.com/57550503/102865570-eee5de00-4470-11eb-93f6-3ae74fd88c74.png)

**Comment by atreyasha** [comment]
> @atreyasha Hello professor, I pulled the code again and re-installed virtual environment with the new requirements.txt file,An error occurred：module 'bert' has no attributue 'fetch_google_albert_models'.

I see. It seems the legacy code did not get deleted. In that case we can try a manual fix.

Try executing `pip uninstall bert erlastic` and then run the code again. This would manually remove the problematic code and the errors should go away after this.

> I modified requirements.txt and change tensorflow-gpu to tensorflow.

I would recommend keeping `tensorflow-gpu` if you intend to use a GPU with the model.

**Comment by qzqzzw** [comment]
@atreyasha Hello professor,I did it this way, but it didn't work.
![1](https://user-images.githubusercontent.com/57550503/102884035-e4850d80-448b-11eb-940c-de13b9d2b4eb.png)

**Comment by atreyasha** [comment]
Can you execute the following python code within your virtual environment and post the output:

```python
import bert
print(bert.__file__)
print(bert.__version__)
dir(bert)
```

**Comment by qzqzzw** [comment]
![1](https://user-images.githubusercontent.com/57550503/102887232-83603880-4491-11eb-95d9-4af3ca71b501.png)

**Comment by atreyasha** [comment]
Okay so it appears `bert` is loaded as a module but is empty. I can't reproduce this, so not sure why this happens. Might be related to `anaconda`. Could you execute this python code:

```python
import bert
print(bert.__path__)
```

Could you execute the following `shell` command:

```shell
tree /home/shipengfei/anaconda3/envs/tensorflow/lib/python3.7/site-packages/bert
```

**Comment by qzqzzw** [comment]
![1](https://user-images.githubusercontent.com/57550503/102888694-3e89d100-4494-11eb-96e8-70561750e40c.png)

**Comment by qzqzzw** [comment]
@atreyasha 
![1](https://user-images.githubusercontent.com/57550503/102888750-595c4580-4494-11eb-9f0a-507247461aed.png)

**Comment by qzqzzw** [comment]
@atreyasha 
![2](https://user-images.githubusercontent.com/57550503/102888935-a7714900-4494-11eb-8beb-4463908915a2.png)
![1](https://user-images.githubusercontent.com/57550503/102888939-a8a27600-4494-11eb-8d26-c6b3bd7f073c.png)

**Comment by atreyasha** [comment]
The `bert` source code is the same on both our machines, so it seems something is broken in the virtual environment. Can you try executing the following to purge and re-initialize the virtual environment:

```shell
# leave the tensorflow environment
conda deactivate

# delete the tensorflow environment
conda remove --name tensorflow --all

# re-create the tensorflow environment
conda create -n tensorflow python=3.7

# activate the environment
conda activate tensorflow

# install python packages again
pip install -r requirements.txt
```

After this, run the python scripts to see if they work. I hope this one does it.

**Comment by qzqzzw** [comment]
@atreyasha Hello professor,I re-initialize the virtual environment.I execute  `python3 pre_process_USElectionDebates.py`,but a problem arises：Error loading punkt.
![1](https://user-images.githubusercontent.com/57550503/102951140-12f3fe80-4507-11eb-85e0-57dc2fd238ce.png)

**Comment by atreyasha** [comment]
This means the `nltk` tokenizer library is missing and you need to manually download it. I see you tried to download it below, but you spelt `punkt` as `pinkt`. It should be:

```python
import nltk
nltk.download('punkt')
```

After it downloads you can re-run the script.

**Comment by qzqzzw** [comment]
@atreyasha  Hello professor,I’m sorry that I cut the wrong picture, I spelled it correctly and Error loading punkt still appears.
![1](https://user-images.githubusercontent.com/57550503/102995577-53319c00-455c-11eb-9632-5cef1f8d6b6b.png)

**Comment by atreyasha** [comment]
It seems your connection to download the data is being blocked, perhaps by your machine/firewall. I'm afraid I cannot help with this because this is very specific to your use-case.

I would suggest looking into alternative means of downloading this data. A quick search would yield similar queries such as: https://stackoverflow.com/a/45507358

**Comment by sw5park** [comment]
> HI @qzqzzw,
> 
> 1. Regarding `pre_process_UNSC.py`, I am not able to reproduce this error when I run it locally. In your case, it appears the file `docs.RData` is found but cannot be read. Could you try deleting `docs.RData` and `docs_meta.RData` and then downloading them again using the `init.sh` script? If this does not work, could you also check the read permissions of the respective `*.RData` files?
> 2. Regarding prediction, try executing the following command:
> 
> ```python
> python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5
> ```
> 
> PS: For the prediction command, you need to have downloaded the model using `git lfs`. If the model `./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5` is not present, try installing `git-lfs` and then run `git lfs pull` in this repository to download the model.
> 
> Hope these help. Let me know if there are still errors and we can work on fixing them.

________________________________________________________________________________--



Hello, I was hoping to get some guidance on the following issue when running **python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5**


2021-04-24 15:24:48,464 | INFO | Loading model predictions, might take some time...
Already  fetched:  albert_base_v2.tar.gz
already unpacked at: .models/albert_base_v2
Traceback (most recent call last):
  File "predict_UNSC.py", line 211, in <module>
    force_pred=args.force_pred)
  File "predict_UNSC.py", line 97, in pred_model_UNSC
    model = load_saved_model(model_path)
  File "predict_UNSC.py", line 69, in load_saved_model
    "argument_candidate_acc": class_acc(3)
  File "/home/sw5park/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/sw5park/venv/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
**OSError: SavedModel file does not exist at: ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5/{saved_model.pbtxt|saved_model.pb}**

**Comment by atreyasha** [comment]
@qzqzzw were you able to resolve the issue and test the model?

**Comment by atreyasha** [comment]
Closing this issue as stale. @qzqzzw feel free to re-open if you have any other queries.
