### ISSUE TITLE
Pre-trained checkpoints/saved model?

### ISSUE THREAD

**Issue by dan-hu-spring** [atreyasha/sentiment-argument-mining#14]
Hello,

I was wondering if it was possible if we could be provided a link to download the checkpoints/saved model to verify the results you guys got. In particular, we are really interested in the argumentation mining model.

Thanks, this looks really interesting!

**Comment by atreyasha** [comment]
Hi @dan-hu-spring.

Apologies that our readme was a bit convoluted. I updated the readme(s) to provide clearer instructions. The relevant bit for syncing our best performing argumentation mining model can be found here:

https://github.com/atreyasha/sentiment-argument-mining#pre-trained-argumentation-model

Let me know in case you encounter any problems.

**Comment by dan-hu-spring** [comment]
Thank you, found it.
