### ISSUE TITLE
Prediction on UNSC using best model

### ISSUE THREAD

**Issue by sw5park** [atreyasha/sentiment-argument-mining#15]
Hello, I am recreating the following:

To run this script on our best model, simply execute:

**$ python3 predict_UNSC.py --model ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5**

receive the following error:

2021-04-24 14:46:21,213 | INFO | Loading model predictions, might take some time...
Already  fetched:  albert_base_v2.tar.gz
already unpacked at: .models/albert_base_v2
Traceback (most recent call last):
  File "predict_UNSC.py", line 211, in <module>
    force_pred=args.force_pred)
  File "predict_UNSC.py", line 97, in pred_model_UNSC
    model = load_saved_model(model_path)
  File "predict_UNSC.py", line 69, in load_saved_model
    "argument_candidate_acc": class_acc(3)
  File "/home/sw5park/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/sw5park/venv/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
**OSError: SavedModel file does not exist at: ./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5/{saved_model.pbtxt|saved_model.pb}**

Would appreciate any support, thank you !

**Comment by atreyasha** [comment]
Hi @sw5park,

Thanks for reaching out and sending the traceback. I can reproduce this error when I remove the best performing model at `./model_logs/2020_03_17_09_17_44_MSL512_grid_train/model_1.h5`. This would imply that the best performing model is not present in your cloned repository.

I updated our readme to provide clearer instructions and the relevant portion for syncing the best model can be found here:

https://github.com/atreyasha/sentiment-argument-mining#pre-trained-argumentation-model

Let me know in case you encounter further problems.

**Comment by sw5park** [comment]
@atreyasha 

Thank you very much, the problem is fixed.

Within your final report (sentiment-argument-mining/docs/final_report/main.pdf) section 5.2.2 Prediction on UNSC, do you have the codebase for the coloring scheme given the human-readable json file (e.g. pred_clean_512.json) ?
